#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prog.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prog.y"
	
	#include <stdio.h>
	#include <stdlib.h>
	#include <stdarg.h>
	#include <string.h>
	#include "include/AST.h"
	#include "include/BaseOperations.h"
	
	int H, W;
	
	#define size_x 10
	#define size_y 10
	
	int int_vars[100] = {};
	Node* ptpos[100] = {};
	Node* funcPtr[100] = {};
	Array* arrays[100] = {};
	Array* attachFunctions[100] = {};
	char isUsed[100] = {};
	
	int robot_pos_X = 0;
	int robot_pos_Y = 0;
	
	char map[size_x][size_y];
	
	FILE* pTreeFile;
	FILE* path;
	
	int yylex(void);
	
	void printTree(char* prefix, const Node* p, char isLeft);
	void printBT(const Node* node);
	void findRandomPoint(int* x,int* y);
	void writeStep(FILE* f_ptr);
	
	typedef enum {
		IF,
		WHILE,
		GOTO,
		EXEC
	} NT;

#line 44 "prog.y"
typedef union {
	int value;                 /* integer value */
	int id;					/* integer id   */
	char* str;
	Node* node_ptr;             /* node pointer */
	Tuple* tuple_ptr;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	VAR	259
#define	POINT	260
#define	INT_ARR	261
#define	BOOL_ARR	262
#define	FUNC_ARR	263
#define	FUNC	264
#define	STR	265
#define	EQ	266
#define	NOR	267
#define	ASSIGN	268
#define	END	269
#define	ATTACH	270
#define	DETACH	271
#define	DOUBLE_OPEN	272
#define	DOUBLE_CLOSE	273
#define	MV_FRONT	274
#define	MV_BACK	275
#define	MV_LEFT	276
#define	MV_RIGHT	277
#define	TELEPORT	278
#define	INC	279
#define	DEC	280
#define	DEBUG	281
#define	MSG	282
#define	PASS	283
#define	PLEASE	284
#define	UMINUS	285


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int VAR;
static const int POINT;
static const int INT_ARR;
static const int BOOL_ARR;
static const int FUNC_ARR;
static const int FUNC;
static const int STR;
static const int EQ;
static const int NOR;
static const int ASSIGN;
static const int END;
static const int ATTACH;
static const int DETACH;
static const int DOUBLE_OPEN;
static const int DOUBLE_CLOSE;
static const int MV_FRONT;
static const int MV_BACK;
static const int MV_LEFT;
static const int MV_RIGHT;
static const int TELEPORT;
static const int INC;
static const int DEC;
static const int DEBUG;
static const int MSG;
static const int PASS;
static const int PLEASE;
static const int UMINUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,VAR=259
	,POINT=260
	,INT_ARR=261
	,BOOL_ARR=262
	,FUNC_ARR=263
	,FUNC=264
	,STR=265
	,EQ=266
	,NOR=267
	,ASSIGN=268
	,END=269
	,ATTACH=270
	,DETACH=271
	,DOUBLE_OPEN=272
	,DOUBLE_CLOSE=273
	,MV_FRONT=274
	,MV_BACK=275
	,MV_LEFT=276
	,MV_RIGHT=277
	,TELEPORT=278
	,INC=279
	,DEC=280
	,DEBUG=281
	,MSG=282
	,PASS=283
	,PLEASE=284
	,UMINUS=285


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::VAR=259;
const int YY_parse_CLASS::POINT=260;
const int YY_parse_CLASS::INT_ARR=261;
const int YY_parse_CLASS::BOOL_ARR=262;
const int YY_parse_CLASS::FUNC_ARR=263;
const int YY_parse_CLASS::FUNC=264;
const int YY_parse_CLASS::STR=265;
const int YY_parse_CLASS::EQ=266;
const int YY_parse_CLASS::NOR=267;
const int YY_parse_CLASS::ASSIGN=268;
const int YY_parse_CLASS::END=269;
const int YY_parse_CLASS::ATTACH=270;
const int YY_parse_CLASS::DETACH=271;
const int YY_parse_CLASS::DOUBLE_OPEN=272;
const int YY_parse_CLASS::DOUBLE_CLOSE=273;
const int YY_parse_CLASS::MV_FRONT=274;
const int YY_parse_CLASS::MV_BACK=275;
const int YY_parse_CLASS::MV_LEFT=276;
const int YY_parse_CLASS::MV_RIGHT=277;
const int YY_parse_CLASS::TELEPORT=278;
const int YY_parse_CLASS::INC=279;
const int YY_parse_CLASS::DEC=280;
const int YY_parse_CLASS::DEBUG=281;
const int YY_parse_CLASS::MSG=282;
const int YY_parse_CLASS::PASS=283;
const int YY_parse_CLASS::PLEASE=284;
const int YY_parse_CLASS::UMINUS=285;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		80
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 285 ? yytranslate[x] : 46)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    32,
    33,     2,     2,     2,    36,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    31,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    34,     2,    35,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     6,     8,    12,    14,    18,    22,    24,
    26,    28,    31,    34,    38,    42,    46,    50,    54,    58,
    63,    69,    74,    78,    81,    83,    86,    88,    92,    94,
    96,    99,   101,   104,   107,   109,   111,   113,   115,   117,
   120,   124,   128
};

static const short yyrhs[] = {    38,
     0,    43,    14,     0,     0,     9,     0,     8,    31,    44,
     0,     4,     0,     6,    31,    44,     0,     7,    31,    44,
     0,    39,     0,    40,     0,    45,     0,    26,    45,     0,
    27,    10,     0,    39,    13,    42,     0,    39,    13,    39,
     0,    40,    13,    45,     0,    41,    15,    39,     0,    41,
    16,    39,     0,    39,    32,    33,     0,    17,    45,    18,
    42,     0,    17,    45,    18,    29,     5,     0,    32,    45,
    33,    42,     0,    34,    43,    35,     0,     5,    43,     0,
    42,     0,    43,    42,     0,    45,     0,    44,    36,    45,
     0,     3,     0,    41,     0,    36,    45,     0,    28,     0,
    24,     3,     0,    25,     3,     0,    19,     0,    20,     0,
    21,     0,    22,     0,    23,     0,    12,    45,     0,    12,
    45,    45,     0,    45,    11,    45,     0,    32,    45,    33,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    70,    76,    89,    92,    96,   103,   107,   112,   119,   123,
   128,   133,   137,   141,   145,   149,   154,   159,   163,   167,
   171,   175,   179,   183,   189,   194,   201,   209,   220,   225,
   229,   233,   238,   242,   247,   251,   255,   259,   263,   267,
   271,   275,   279
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","VAR",
"POINT","INT_ARR","BOOL_ARR","FUNC_ARR","FUNC","STR","EQ","NOR","ASSIGN","END",
"ATTACH","DETACH","DOUBLE_OPEN","DOUBLE_CLOSE","MV_FRONT","MV_BACK","MV_LEFT",
"MV_RIGHT","TELEPORT","INC","DEC","DEBUG","MSG","PASS","PLEASE","UMINUS","':'",
"'('","')'","'{'","'}'","'-'","program","sentences","function","variable","identifier",
"statement","statementList","dimens","expression",""
};
#endif

static const short yyr1[] = {     0,
    37,    38,    38,    39,    39,    40,    40,    40,    41,    41,
    42,    42,    42,    42,    42,    42,    42,    42,    42,    42,
    42,    42,    42,    42,    43,    43,    44,    44,    45,    45,
    45,    45,    45,    45,    45,    45,    45,    45,    45,    45,
    45,    45,    45
};

static const short yyr2[] = {     0,
     1,     2,     0,     1,     3,     1,     3,     3,     1,     1,
     1,     2,     2,     3,     3,     3,     3,     3,     3,     4,
     5,     4,     3,     2,     1,     2,     1,     3,     1,     1,
     2,     1,     2,     2,     1,     1,     1,     1,     1,     2,
     3,     3,     3
};

static const short yydefact[] = {     3,
    29,     6,     0,     0,     0,     0,     4,     0,     0,    35,
    36,    37,    38,    39,     0,     0,     0,     0,    32,     0,
     0,     0,     1,     9,    10,    30,    25,     0,    11,    24,
     0,     0,     0,     0,     9,    10,    30,    40,     0,    33,
    34,    12,    13,     0,     0,    31,     0,     0,     0,     0,
     0,     2,    26,     0,     7,    27,     8,     5,     0,    41,
     0,    43,    23,     9,    14,    19,    16,    17,    18,    42,
     0,    43,     0,    20,    22,    28,    21,     0,     0,     0
};

static const short yydefgoto[] = {    78,
    23,    35,    36,    37,    27,    28,    55,    29
};

static const short yypact[] = {   187,
-32768,-32768,   187,   -25,   -23,    -2,-32768,   221,   221,-32768,
-32768,-32768,-32768,-32768,    17,    31,   221,    28,-32768,   221,
   187,   221,-32768,   -11,    29,   -12,-32768,    85,    33,   187,
   221,   221,   221,   221,-32768,-32768,-32768,   252,    21,-32768,
-32768,    33,-32768,    -6,   119,-32768,   187,    23,   221,     8,
     8,-32768,-32768,   221,    12,    33,    12,    12,     0,-32768,
   153,   187,-32768,   -11,-32768,-32768,    33,-32768,-32768,-32768,
   221,-32768,    54,-32768,-32768,    33,-32768,    61,    65,-32768
};

static const short yypgoto[] = {-32768,
-32768,     7,    15,    19,    25,    10,    18,    -8
};


#define	YYLAST		288


static const short yytable[] = {    38,
    39,    47,    50,    51,    54,    31,    24,    32,    42,    24,
    54,    44,    30,    46,    25,     6,     7,    25,    26,    40,
    48,    26,    56,    56,    56,    59,    62,    24,    33,    60,
    45,    54,    72,    41,    24,    25,    24,    43,    61,    26,
    67,    49,    25,    54,    25,    70,    26,    71,    26,    57,
    58,    24,    53,    64,    53,    66,    68,    69,    77,    25,
    79,    25,    76,    26,    80,    26,     0,    24,    24,    53,
     0,    65,     0,     0,     0,    25,    25,     0,     0,    26,
    26,     0,     0,     0,     0,    74,    75,     1,     2,     3,
     4,     5,     6,     7,     0,     0,     8,     0,    52,     0,
     0,     9,     0,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    19,     0,     0,     0,    20,     0,    21,     0,
    22,     1,     2,     3,     4,     5,     6,     7,     0,     0,
     8,     0,     0,     0,     0,     9,     0,    10,    11,    12,
    13,    14,    15,    16,    17,    18,    19,     0,     0,     0,
    20,     0,    21,    63,    22,     1,     2,     3,     4,     5,
     6,     7,     0,     0,     8,     0,     0,     0,     0,     9,
     0,    10,    11,    12,    13,    14,    15,    16,    17,    18,
    19,    73,     0,     0,    20,     0,    21,     0,    22,     1,
     2,     3,     4,     5,     6,     7,     0,     0,     8,     0,
     0,     0,     0,     9,     0,    10,    11,    12,    13,    14,
    15,    16,    17,    18,    19,     0,     0,     0,    20,     0,
    21,     0,    22,     1,     2,     0,     4,     5,     6,     7,
     0,     0,     8,     0,     0,     0,     0,     0,     0,    10,
    11,    12,    13,    14,    15,    16,     0,     0,    19,     0,
     0,     0,    34,     0,     1,     2,    22,     4,     5,     6,
     7,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    10,    11,    12,    13,    14,    15,    16,     0,     0,    19,
     0,     0,     0,    34,     0,     0,     0,    22
};

static const short yycheck[] = {     8,
     9,    13,    15,    16,    11,    31,     0,    31,    17,     3,
    11,    20,     3,    22,     0,     8,     9,     3,     0,     3,
    32,     3,    31,    32,    33,    34,    33,    21,    31,    38,
    21,    11,    33,     3,    28,    21,    30,    10,    18,    21,
    49,    13,    28,    11,    30,    54,    28,    36,    30,    32,
    33,    45,    28,    47,    30,    33,    50,    51,     5,    45,
     0,    47,    71,    45,     0,    47,    -1,    61,    62,    45,
    -1,    47,    -1,    -1,    -1,    61,    62,    -1,    -1,    61,
    62,    -1,    -1,    -1,    -1,    61,    62,     3,     4,     5,
     6,     7,     8,     9,    -1,    -1,    12,    -1,    14,    -1,
    -1,    17,    -1,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    -1,    -1,    -1,    32,    -1,    34,    -1,
    36,     3,     4,     5,     6,     7,     8,     9,    -1,    -1,
    12,    -1,    -1,    -1,    -1,    17,    -1,    19,    20,    21,
    22,    23,    24,    25,    26,    27,    28,    -1,    -1,    -1,
    32,    -1,    34,    35,    36,     3,     4,     5,     6,     7,
     8,     9,    -1,    -1,    12,    -1,    -1,    -1,    -1,    17,
    -1,    19,    20,    21,    22,    23,    24,    25,    26,    27,
    28,    29,    -1,    -1,    32,    -1,    34,    -1,    36,     3,
     4,     5,     6,     7,     8,     9,    -1,    -1,    12,    -1,
    -1,    -1,    -1,    17,    -1,    19,    20,    21,    22,    23,
    24,    25,    26,    27,    28,    -1,    -1,    -1,    32,    -1,
    34,    -1,    36,     3,     4,    -1,     6,     7,     8,     9,
    -1,    -1,    12,    -1,    -1,    -1,    -1,    -1,    -1,    19,
    20,    21,    22,    23,    24,    25,    -1,    -1,    28,    -1,
    -1,    -1,    32,    -1,     3,     4,    36,     6,     7,     8,
     9,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    19,    20,    21,    22,    23,    24,    25,    -1,    -1,    28,
    -1,    -1,    -1,    32,    -1,    -1,    -1,    36
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 71 "prog.y"
{
			printf("Input accepted\n"); exit(0);
		;
    break;}
case 2:
#line 77 "prog.y"
{
			printf("\nstatementList -> sentences\n");
			path = fopen("path.solution", "w");
			writeStep(path);
			execute(yyvsp[-1].node_ptr);
			pTreeFile = fopen("outTree.txt", "w");
			printBT(yyvsp[-1].node_ptr);
			fprintf(path, "\n");
			fclose(pTreeFile);
			fclose(path);
			printf("\nTree has been build\n")
		;
    break;}
case 4:
#line 93 "prog.y"
{
			yyval.node_ptr = createFuncNode(yyvsp[0].id);
		;
    break;}
case 5:
#line 97 "prog.y"
{
			printf("\nFUNC_ARR : dimens -> function\n");
			yyval.node_ptr = createArrElemNode(yyvsp[-2].id, FuncElem, yyvsp[0].tuple_ptr);
		;
    break;}
case 6:
#line 104 "prog.y"
{
			yyval.node_ptr = createVarNode(yyvsp[0].id);
		;
    break;}
case 7:
#line 108 "prog.y"
{
			printf("\nINT_ARR : dimens -> variable\n");
			yyval.node_ptr = createArrElemNode(yyvsp[-2].id, IntElem, yyvsp[0].tuple_ptr);
		;
    break;}
case 8:
#line 113 "prog.y"
{
			printf("\nBOOL_ARR : dimens -> variable\n");
			yyval.node_ptr = createArrElemNode(yyvsp[-2].id, BoolElem, yyvsp[0].tuple_ptr);
		;
    break;}
case 9:
#line 120 "prog.y"
{
			yyval.node_ptr = yyvsp[0].node_ptr;
		;
    break;}
case 10:
#line 124 "prog.y"
{
			yyval.node_ptr = yyvsp[0].node_ptr;
		;
    break;}
case 11:
#line 129 "prog.y"
{
			printf("\n expression -> statement\n");
			yyval.node_ptr = yyvsp[0].node_ptr;
		;
    break;}
case 12:
#line 134 "prog.y"
{
			yyval.node_ptr = createOpNode(DEBUG, 1, yyvsp[0].node_ptr);
		;
    break;}
case 13:
#line 138 "prog.y"
{
			yyval.node_ptr = createOpNode(MSG, 1, createStrNode(yyvsp[0].str));
		;
    break;}
case 14:
#line 142 "prog.y"
{
			yyval.node_ptr = createOpNode(ASSIGN, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 15:
#line 146 "prog.y"
{
			yyval.node_ptr = createOpNode(ASSIGN, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 16:
#line 150 "prog.y"
{
			printf("\nvariable ASSIGN expression -> statement\n");
			yyval.node_ptr = createOpNode(ASSIGN, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 17:
#line 155 "prog.y"
{
			printf("\nidentifier ATTACH function -> statement\n");
			yyval.node_ptr = createOpNode(ATTACH, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 18:
#line 160 "prog.y"
{
			yyval.node_ptr = createOpNode(DETACH, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 19:
#line 164 "prog.y"
{
			yyval.node_ptr = createOpNode(EXEC, 1, yyvsp[-2].node_ptr);
		;
    break;}
case 20:
#line 168 "prog.y"
{
			yyval.node_ptr = createOpNode(IF, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 21:
#line 172 "prog.y"
{
			yyval.node_ptr = createOpNode(GOTO, 2, yyvsp[-3].node_ptr, createPointNode(yyvsp[0].id));
		;
    break;}
case 22:
#line 176 "prog.y"
{
			yyval.node_ptr = createOpNode(WHILE, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 23:
#line 180 "prog.y"
{
			yyval.node_ptr = yyvsp[-1].node_ptr;
		;
    break;}
case 24:
#line 184 "prog.y"
{	
			yyval.node_ptr = createOpNode(POINT, 2, createPointNode(yyvsp[-1].id), yyvsp[0].node_ptr);
		;
    break;}
case 25:
#line 190 "prog.y"
{
			printf("\nstatement -> statementList\n");
			yyval.node_ptr = yyvsp[0].node_ptr;
		;
    break;}
case 26:
#line 195 "prog.y"
{
			printf("\nstatementList statement -> statementList\n");
			yyval.node_ptr = createOpNode(EXEC, 2, yyvsp[-1].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 27:
#line 202 "prog.y"
{
			printf("\nexpresion -> dimens\n");
			yyval.tuple_ptr = malloc(sizeof(Tuple));
			yyval.tuple_ptr->values = malloc(1 * sizeof(Node*));
			yyval.tuple_ptr->values[0] = yyvsp[0].node_ptr;
			yyval.tuple_ptr->size = 1;
		;
    break;}
case 28:
#line 210 "prog.y"
{
			int length = yyvsp[-2].tuple_ptr->size;
			yyval.tuple_ptr = yyvsp[-2].tuple_ptr;
			yyval.tuple_ptr->values = realloc(yyval.tuple_ptr->values, (length + 1) * sizeof(Node*));
			yyval.tuple_ptr->values[length] = yyvsp[0].node_ptr;
			(yyval.tuple_ptr->size)++;
			printf("\ndimens - expression -> dimens\n");
		;
    break;}
case 29:
#line 221 "prog.y"
{
			printf("\nINT -> expression\n");
			yyval.node_ptr = createConstantNode(yyvsp[0].value);
		;
    break;}
case 30:
#line 226 "prog.y"
{
			yyval.node_ptr = yyvsp[0].node_ptr;
		;
    break;}
case 31:
#line 230 "prog.y"
{
			yyval.node_ptr = createOpNode(UMINUS, 1, yyvsp[0].node_ptr);
		;
    break;}
case 32:
#line 234 "prog.y"
{
			printf("\nPASS -> expression\n");
			yyval.node_ptr = createOpNode(PASS, 0);
		;
    break;}
case 33:
#line 239 "prog.y"
{
			yyval.node_ptr = createOpNode(INC, 1, createVarNode(yyvsp[0].value));
		;
    break;}
case 34:
#line 243 "prog.y"
{
			printf("\nDEC INT -> expression\n");
			yyval.node_ptr = createOpNode(DEC, 1, createVarNode(yyvsp[0].value));
		;
    break;}
case 35:
#line 248 "prog.y"
{
			yyval.node_ptr = createOpNode(MV_FRONT, 0);
		;
    break;}
case 36:
#line 252 "prog.y"
{
			yyval.node_ptr = createOpNode(MV_BACK, 0);
		;
    break;}
case 37:
#line 256 "prog.y"
{
			yyval.node_ptr = createOpNode(MV_LEFT, 0);
		;
    break;}
case 38:
#line 260 "prog.y"
{
			yyval.node_ptr = createOpNode(MV_RIGHT, 0);
		;
    break;}
case 39:
#line 264 "prog.y"
{
			yyval.node_ptr = createOpNode(TELEPORT, 0);
		;
    break;}
case 40:
#line 268 "prog.y"
{
			yyval.node_ptr = createOpNode(NOR, 1, yyvsp[0].node_ptr);
		;
    break;}
case 41:
#line 272 "prog.y"
{
			yyval.node_ptr = createOpNode(NOR, 2, yyvsp[-1].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 42:
#line 276 "prog.y"
{
			yyval.node_ptr = createOpNode(EQ, 2, yyvsp[-2].node_ptr, yyvsp[0].node_ptr);
		;
    break;}
case 43:
#line 280 "prog.y"
{
			yyval.node_ptr = yyvsp[-1].node_ptr;
		;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 284 "prog.y"


long execute(Node* p) {
	if (!p) return 0;
	switch (p->type) {
	case Constant:  return p->constant.value;
	case Variable:  return int_vars[p->var.id];
	case Point: return p->ptpos.id;
	case Function:
		{
			int func_id = p->func.id;
			execute(funcPtr[func_id]);
			return 0L;
		}
	case ArrElem:
		{
			int i, arr_id = p->arr.id;
			int n_dim = p->arr.n_dim;
			if (arrays[arr_id] == NULL) {
				alloc_array(arr_id, p->arr.type, n_dim, p->arr.idxs);
			}
			Array* arr = arrays[arr_id];
			//compute index;
			int factor = 1;
			for (i = 0; i < arr->n_dim; ++i) {
				factor *= arr->dimens[i];
			}
			
			int index = 0;
			for (i = 0; i < n_dim; ++i) {
				factor /= arr->dimens[i];
				index += execute(p->arr.idxs[i]) * factor;
			}
			switch(p->arr.type) {
				case IntElem: case BoolElem:
					return (long)arrays[arr_id]->values[index];
				case FuncElem:
					return (long)arrays[arr_id]->functions[index];
			}
		}
	case Operator:
		switch (p->op.id) {
		case WHILE:
		{
			while (execute(p->op.operands[0]))
				execute(p->op.operands[1]);
			return 0L;
		}
		case IF:
		{
			if (execute(p->op.operands[0]))
				execute(p->op.operands[1]);
			return 0L;
		}
		case POINT:
		{
			execute(ptpos[p->op.operands[0]->ptpos.id] = p->op.operands[1]);
			return 0L;
		}
		case NOR:
		{
			switch(p->op.noperands) {
				case 1: return !execute(p->op.operands[0]);
				case 2: return !execute(p->op.operands[0]) && !execute(p->op.operands[1]);
			}
		}
		case GOTO:
		{
			if (execute(p->op.operands[0])) {
				execute(ptpos[execute(p->op.operands[1])]);
				return -1L;
			}
			return 0L;
		}
		case UMINUS:
		{
			return -execute(p->op.operands[0]);
		}
		case DEBUG:
		{
			switch(p->op.operands[0]->type) {
				case ArrElem: call_attach_functions(p->op.operands[0]->arr.id); break;
				case Variable: call_attach_functions(p->op.operands[0]->var.id); break;
				case Function: call_attach_functions(p->op.operands[0]->func.id); break;
			}
			
			printf("DEBUG:%ld\n", execute(p->op.operands[0]));
			return 0L;
		}
		case INC:
		{
			call_attach_functions(p->op.operands[0]->var.id);
			++(int_vars[p->op.operands[0]->var.id]);
			return 0L;
		}
		case DEC:
		{
			call_attach_functions(p->op.operands[0]->var.id);
			--(int_vars[p->op.operands[0]->var.id]);
			return 0L;
		}
		case MV_FRONT:
			{	
				printf("Current x_pos: %d\n", robot_pos_X);
				if (robot_pos_X > 0 && map[robot_pos_X - 1][robot_pos_Y] != 'X') {
					map[robot_pos_X][robot_pos_Y] = '1';
					robot_pos_X--;
					map[robot_pos_X][robot_pos_Y] = 'R';
					writeStep(path);
					return 1L;
				}
				return 0L;
			}
		case MV_BACK:
			{
				printf("Current x_pos: %d\n", robot_pos_X);
				if (robot_pos_X < H - 1 && map[robot_pos_X + 1][robot_pos_Y] != 'X') {
					map[robot_pos_X][robot_pos_Y] = '1';
					robot_pos_X++;
					map[robot_pos_X][robot_pos_Y] = 'R';
					writeStep(path);
					return 1L;
				}
				return 0L;
			}
		case MV_LEFT:
			{
				if (robot_pos_Y > 0 && map[robot_pos_X][robot_pos_Y - 1] != 'X') {
					map[robot_pos_X][robot_pos_Y] = '1';
					robot_pos_Y--;
					map[robot_pos_X][robot_pos_Y] = 'R';
					writeStep(path);
					return 1L;
				}
				return 0L;
			}
		case MV_RIGHT:
			{
				if (robot_pos_Y < W - 1 && map[robot_pos_X][robot_pos_Y + 1] != 'X') {
					map[robot_pos_X][robot_pos_Y] = '1';
					robot_pos_Y++;
					map[robot_pos_X][robot_pos_Y] = 'R';
					writeStep(path);
					return 1L;
				}
				return 0L;
			}
		case TELEPORT:
			{
				int x, y;
				findRandomPoint(&x, &y);
				if (x != -1 && y != -1) {
					map[robot_pos_X][robot_pos_Y] = '1';
					robot_pos_X = x;
					robot_pos_Y = y;
					map[x][y] = 'R';
					writeStep(path);
					printf("\nROBOT HAS BEEN TELEPORTED TO: %d %d\n", x, y);
					return 1L;
				}
				return 0L;
			}
		case PASS:
		{
			return 0L;
		}
		case MSG:
		{	
			printf("\nMESSAGE: %s\n", p->op.operands[0]->str.value);
			return 0L;
		}
		case EXEC:
		{
			switch(p->op.noperands) {
				case 1:
				{
					switch(p->op.operands[0]->type) {
						case ArrElem:
						{
							Node* funcPtr = (Node*) execute(p->op.operands[0]);
							execute(funcPtr);
							return 0L;
						}
						default:
							return execute(p->op.operands[0]);
					}
				}
				case 2:
				{
					if (execute(p->op.operands[0]) >= 0L && execute(p->op.operands[1]) >= 0L) {
						return 0L;
					} else {
						return -1L;
					}
				}
			}
		}
		case ATTACH:
		{
			int Id;
			switch(p->op.operands[0]->type) {
				case ArrElem: Id = p->op.operands[0]->arr.id; break;
				case Variable: Id = p->op.operands[0]->var.id; break;
				case Function: Id = p->op.operands[0]->func.id; break;
			}
			printf("\nATTACH\n");
			if (attachFunctions[Id] == NULL) {
				alloc_attaches(Id);
				attachFunctions[Id]->functions[0] = p->op.operands[1];
				printf("\n%p\n", attachFunctions[Id]->functions[0]);
				return 0L;
			}
			attach(Id, funcPtr[p->op.operands[1]->func.id]);
			return 0L;
		}
		case DETACH:
		{
			int Id;
			switch(p->op.operands[0]->type) {
				case ArrElem: Id = p->op.operands[0]->arr.id; break;
				case Variable: Id = p->op.operands[0]->var.id; break;
				case Function: Id = p->op.operands[0]->func.id; break;
			}
			detach(Id, funcPtr[p->op.operands[1]->func.id]);
			return 0L;
		}
		case ASSIGN:
			switch(p->op.operands[0]->type) {
				case Variable: 
				{
					int_vars[p->op.operands[0]->var.id] = execute(p->op.operands[1]);
					return 0L;
				}
				case Function:
				{	
					int funcId = p->op.operands[0]->func.id;
					switch(p->op.operands[1]->type) {
						case Operator: funcPtr[funcId] = p->op.operands[1]; break;
						case Function: funcPtr[funcId] = funcPtr[p->op.operands[1]->func.id]; break;
					}
					return 0L;
				}
				case ArrElem:
				{
					int index = 0, i = 0;
					int arr_id = p->op.operands[0]->arr.id;
					int n_dim = p->op.operands[0]->arr.n_dim;
					Array* arr = arrays[arr_id];
					int factor = 1;
					for (i = 0; i < arr->n_dim; ++i) {
						factor *= arr->dimens[i];
					}
					
					for (i = 0; i < n_dim; ++i) {
						factor /= arr->dimens[i];
						index += execute(p->op.operands[0]->arr.idxs[i]) * factor;
					}
					
					assign_arr_elem(arr, index, p->op.operands[0], p->op.operands[1]);
					
					return 0L;
				}
			}
		case EQ:
			{
				return compare(p->op.operands[0], p->op.operands[1]);
			}
		}
	}
	return 0L;
}

void printTree(char* prefix, const Node* p, char isLeft)
{
    if( p != NULL )
    {
        fprintf(pTreeFile, "%s", prefix);
		char* newPrefix = malloc(strlen(prefix) + 5);
		memcpy(newPrefix, prefix, strlen(prefix));
		if (isLeft) {
			fprintf(pTreeFile,"|--");
			memcpy(newPrefix + strlen(prefix), "|   ", 5);
		} else {
			fprintf(pTreeFile, "\\__");
			memcpy(newPrefix + strlen(prefix), "    ", 5);
		}
		
		char *s;
		int nops = 0;
		char word[20];
		strcpy (word, "???");
		s = word;
		switch (p->type) {
			case Constant: sprintf(word, "c(%d)", p->constant.value); break;
			case Variable: sprintf(word, "id(%d)", p->var.id); break;
			case Point: sprintf(word, "pt(%d)", p->ptpos.id); break;
			case Function: sprintf(word, "func(id:%d)", p->func.id); break;
			case String: sprintf(word, "%s", p->str.value); break;
			case ArrElem:
			{
				int i = 0, j = 0;
				j = sprintf(word, "arr(%d)[%ld", p->arr.id, execute(p->arr.idxs[0]));
				for (i = 1; i < p->arr.n_dim; ++i) {
					j += sprintf(word + j, "-%ld", execute(p->arr.idxs[i]));
				}
				sprintf(word + j, "]");
				break;
			}
			case Operator:
				nops = p->op.noperands;
				switch (p->op.id) {
					case WHILE: s = "while"; break;
					case IF: s = "if"; break;
					case EXEC: s = "[exec]"; break;
					case GOTO: s = "[goto]"; break;
					case ASSIGN: s = "[<-]"; break;
					case EQ: s = "[eq]"; break;
					case INC: s = "[inc]"; break;
					case DEC: s = "[dec]"; break;
					case ATTACH: s = "[attach]"; break;
					case MSG: s = "[msg]"; break;
					case DETACH: s = "[detach]"; break;
					case MV_FRONT: s = "[mf]"; break;
					case MV_BACK: s = "[mb]"; break;
					case MV_LEFT: s = "[ml]"; break;
					case MV_RIGHT: s = "[mr]"; break;
					case TELEPORT: s = "[tp]"; break;
					case NOR: s = "[nor]"; break;
					case UMINUS: s = "[uminus]"; break;
					case PASS: s = "[pass]"; break;
					case DEBUG: s = "[print]"; break;
					case POINT: s = "[createPt]"; break;
				}
				break;
		}
		switch(nops) {
			case 0:
				fprintf(pTreeFile, "%s\n", s);
				break;
			case 1:
				fprintf(pTreeFile, "%s\n", s);
				printTree( newPrefix, p->op.operands[0], 1);
				break;
			case 2:
				fprintf(pTreeFile, "%s\n", s);
				printTree( newPrefix, p->op.operands[0], 1);
				printTree( newPrefix, p->op.operands[1], 0);
				break;
		}
    }
}

void findRandomPoint(int* x,int* y) {
	for (int i = 0; i < H; ++i) {
		for (int j = 0; j < W; ++j) {
			if (map[i][j] == '0') {
				*x = i;
				*y = j;
				return;
			}
		}
	}
	*x = *y = -1;
}

void writeStep(FILE* f_ptr) {
	fprintf(f_ptr, "%s", "\n\n");
	for (int i = 0; i < H; ++i) {
		for (int j = 0; j < W; ++j) {
			fprintf(f_ptr, "%c", map[i][j]);
		}
		fprintf(f_ptr, "\n");
	}
}

void printBT(const Node* node)
{
	char* prefix = malloc(1);
	prefix[0] = '\0';
    printTree(prefix, node, 0);    
}

void yyerror(char* s) {
	fprintf(stdout, "%s\n", s);
}

#include "lex.yy.c"

int main(int argc, char* argv[])
{
	if (argc > 2)// если передаем аргументы, то argc будет больше 1(в зависимости от кол-ва аргументов)
	{
		if (strcmp(argv[1], "--graphics") == 0) {
			FILE* file = fopen(argv[2], "r");
			fscanf(file, "%d", &H);
			fscanf(file, "%d", &W);
			
			printf("H:%d, W:%d", H, W);
			fgetc(file);
			for (int i = 0; i < H; ++i) {
				fgetc(file);
				for (int j = 0; j < W; ++j) {
					fscanf(file, "%c", &(map[i][j]));
				}
				fgetc(file);
			}
			fclose(file);
			
			for (int i = 0; i < H; ++i) {
				for (int j = 0; j < W; ++j) {
					if (map[i][j] == 'R') {
						robot_pos_X = i;
						robot_pos_Y = j;
					}
				}
			}
			printf("coords: %d %d", robot_pos_X, robot_pos_Y);
		}
	}
	yyparse();
	return 0;
}
